Repository KUSITMS-Team-A/Backend, pull requests merged in 2023-11, with the labels that each got.

#6 [Depoly] 배포 환경 구축
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#8 [Feature] 회원가입, 로그인, 로그아웃, 메일 인증 코드 발송 API 구현
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/backend/common/dto/ResponseDto.java
  src/main/java/com/backend/config/RedisConfig.java
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/auth/controller/AuthController.java
  src/main/java/com/backend/domain/auth/dto/request/JoinRequestDto.java
  src/main/java/com/backend/domain/auth/filter/CustomJsonAuthenticationFilter.java
  src/main/java/com/backend/domain/auth/handler/LoginFailureHandler.java
  src/main/java/com/backend/domain/auth/handler/LoginSuccessHandler.java
  src/main/java/com/backend/domain/auth/service/AuthService.java
  src/main/java/com/backend/domain/auth/service/LoginService.java
  src/main/java/com/backend/domain/mail/controller/MailController.java
  src/main/java/com/backend/domain/mail/dto/request/MailRequest.java
  src/main/java/com/backend/domain/mail/service/MailService.java
  src/main/java/com/backend/domain/user/entity/GroupType.java
  src/main/java/com/backend/domain/user/entity/User.java
  src/main/java/com/backend/domain/user/repository/UserRepository.java
  src/main/java/com/backend/error/ErrorCode.java
  src/main/java/com/backend/error/dto/ErrorResponse.java
  src/main/java/com/backend/error/exception/GlobalExceptionHandler.java
  src/main/java/com/backend/error/exception/custom/BusinessException.java
  src/main/java/com/backend/error/exception/custom/TokenException.java
  src/main/java/com/backend/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/backend/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/backend/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/jwt/service/JwtService.java
  src/main/java/com/backend/util/RedisUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature

#12 [#11] JWT 및 사용자 로그인 관련 기능 수정
  build.gradle
  src/main/java/com/backend/config/RedisConfig.java
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/auth/controller/AuthController.java
  src/main/java/com/backend/domain/auth/dto/Login.java
  src/main/java/com/backend/domain/auth/dto/LoginUser.java
  src/main/java/com/backend/domain/auth/dto/request/JoinRequestDto.java
  src/main/java/com/backend/domain/auth/dto/request/LoginRequestDto.java
  src/main/java/com/backend/domain/auth/handler/LoginFailureHandler.java
  src/main/java/com/backend/domain/auth/handler/LoginSuccessHandler.java
  src/main/java/com/backend/domain/auth/service/AuthService.java
  src/main/java/com/backend/domain/user/entity/User.java
  src/main/java/com/backend/domain/user/repository/UserRepository.java
  src/main/java/com/backend/error/ErrorCode.java
  src/main/java/com/backend/jwt/filter/ApiAccessDeniedHandler.java
  src/main/java/com/backend/jwt/filter/ApiAuthenticationEntryPoint.java
  src/main/java/com/backend/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/jwt/service/ApiUserDetailsService.java
  src/main/java/com/backend/jwt/service/JwtProvider.java
  src/main/java/com/backend/jwt/service/JwtService.java
  src/main/java/com/backend/jwt/token/AccessToken.java
  src/main/java/com/backend/jwt/token/RefreshToken.java
  src/main/java/com/backend/jwt/token/Token.java
Labels: 🔨 Refactor

#10 [#9] Swagger 문서 추가
  build.gradle
  src/main/java/com/backend/config/SwaggerConfig.java
Labels: 📃 Docs

#14 [#13] 토큰이 만료될 경우 401에러를 반환한다.
  build.gradle
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/auth/controller/AuthController.java
  src/main/java/com/backend/domain/auth/dto/LoginUser.java
  src/main/java/com/backend/domain/auth/service/AuthService.java
  src/main/java/com/backend/error/ErrorCode.java
  src/main/java/com/backend/jwt/filter/ApiAuthenticationEntryPoint.java
  src/main/java/com/backend/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/jwt/service/JwtProvider.java
  src/main/java/com/backend/util/LoginUserArgumentResolver.java
Labels: 🔨 Refactor

#17 [Feature] S3 이미지 관리 기능을 추가하고 사용자 도메인과 연동
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/java/com/backend/config/S3Config.java
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/auth/dto/request/JoinRequestDto.java
  src/main/java/com/backend/domain/s3/controller/S3Controller.java
  src/main/java/com/backend/domain/s3/service/S3Service.java
  src/main/java/com/backend/domain/user/entity/User.java
  src/main/java/com/backend/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ Feature

#20 [#19] Feature: 문자 인증 코드를 전송합니다.
  build.gradle
  settings.gradle
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/mail/controller/MailController.java
  src/main/java/com/backend/domain/mail/dto/request/SmsRequest.java
  src/main/java/com/backend/domain/mail/service/MailService.java
  src/main/java/com/backend/error/ErrorCode.java
Labels: ✨ Feature

#23 [#22] 가게 찾기 API 수정
  src/main/java/com/backend/domain/store/dto/ReadStoreDetailsDto.java
  src/main/java/com/backend/domain/store/dto/StoreDetailsDto.java
  src/main/java/com/backend/domain/store/dto/StoresDto.java
  src/main/java/com/backend/domain/store/repository/StoreRepository.java
Labels: 🐞 BugFix

#28 [#25] 가게 제휴 API 구현
  src/main/java/com/backend/domain/benefit/entity/Benefit.java
  src/main/java/com/backend/domain/benefit/entity/BenefitType.java
  src/main/java/com/backend/domain/contract/controller/ContractController.java
  src/main/java/com/backend/domain/contract/dto/BenefitDto.java
  src/main/java/com/backend/domain/contract/dto/CreateBenefitRequest.java
  src/main/java/com/backend/domain/contract/dto/CreateContractRequest.java
  src/main/java/com/backend/domain/contract/dto/ReadContractDetailsDto.java
  src/main/java/com/backend/domain/contract/dto/ReadContractDto.java
  src/main/java/com/backend/domain/contract/dto/ReadContractsDto.java
  src/main/java/com/backend/domain/contract/dto/UpdateBenefitRequest.java
  src/main/java/com/backend/domain/contract/dto/UpdateContractRequest.java
  src/main/java/com/backend/domain/contract/dto/VisitInfo.java
  src/main/java/com/backend/domain/contract/entity/Contract.java
  src/main/java/com/backend/domain/contract/entity/Event.java
  src/main/java/com/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/backend/domain/contract/service/ContractService.java
  src/main/java/com/backend/domain/store/controller/StoreController.java
  src/main/java/com/backend/domain/store/dto/ReadRequest.java
  src/main/java/com/backend/domain/store/service/StoreService.java
Labels: ✨ Feature

#27 [#26] Feature: 각 대학 이름과 메일 형식을 조회하는 기능 추가
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/university/controller/UniversityController.java
  src/main/java/com/backend/domain/university/dto/response/getUnivResponseDto.java
  src/main/java/com/backend/domain/university/entity/University.java
  src/main/java/com/backend/domain/university/repository/UniversityRepository.java
  src/main/java/com/backend/domain/university/service/UniversityService.java
Labels: ✨ Feature

#37 [#36] Refactor: 사용자가 회원가입 할 때 대학도 저장하도록 한다.
  src/main/java/com/backend/domain/auth/controller/AuthController.java
  src/main/java/com/backend/domain/auth/dto/request/JoinRequestDto.java
  src/main/java/com/backend/domain/auth/service/AuthService.java
  src/main/java/com/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/backend/domain/popup/controller/PopupController.java
  src/main/java/com/backend/domain/popup/repository/PopupRepository.java
  src/main/java/com/backend/domain/s3/controller/S3Controller.java
  src/main/java/com/backend/domain/university/dto/response/getUnivResponseDto.java
  src/main/java/com/backend/domain/university/entity/University.java
  src/main/java/com/backend/domain/user/entity/User.java
  src/main/java/com/backend/error/ErrorCode.java
Labels: 🔨 Refactor

#42 [#39] 이벤트 삭제 기능 추가
  src/main/java/com/backend/domain/benefit/entity/BenefitType.java
  src/main/java/com/backend/domain/event/controller/EventController.java
  src/main/java/com/backend/domain/event/dto/CreateEventRequest.java
  src/main/java/com/backend/domain/event/dto/ReadEventDto.java
  src/main/java/com/backend/domain/event/dto/ReadEventsRequest.java
  src/main/java/com/backend/domain/event/entity/Event.java
  src/main/java/com/backend/domain/event/entity/EventType.java
  src/main/java/com/backend/domain/event/repository/EventRepository.java
  src/main/java/com/backend/domain/event/service/EventService.java
Labels: ✨ Feature

#41 [#40] Fix: CORS allowedOrigins 수정
  src/main/java/com/backend/config/SecurityConfig.java
  src/main/java/com/backend/domain/auth/dto/request/JoinRequestDto.java
  src/main/java/com/backend/jwt/filter/JwtAuthenticationFilter.java
Labels: 🐞 BugFix

#44 [#43] Refactor: 팝업 조회할 때 내용에 팝업 아이디 추가
  src/main/java/com/backend/domain/popup/dto/response/PopupGetResponseDto.java
Labels: 🔨 Refactor
